### ISSUE TITLE
Parametry modulu

### ISSUE THREAD

**Issue by ChroustJan** [ThunderFly-aerospace/TFGPS01#1]
Počítat s interní anténou a možností připojit lepší externí.

Rozměry cca:
Size (mm):50x50x11
weight: 28g

Maximální rozměr 70x50mm

**Comment by kaklik** [comment]
Tyhle parametry asi nemohou být s použitím lepší patch antény z #3  dodrženy. 

Přepínání antény asi bude potřeba řešit buď softwarově a nebo nějakým jumperem.

**Comment by ChroustJan** [comment]
Aplikováno
