### ISSUE TITLE
Možnost připojení payloadu k GPS

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFGPS01#10]
Protože je velmi pravděpodobné, že payload bude potřebovat také přístup k datům z GPS, tak by bylo vhodné, aby GPS modul umožnil paralelní připojení i k payloadu. V opačném případě by bylo nutné, aby payload měl vlastní GPS, což ale komplikuje integraci payloadu i zvětšuje hmotnost. 

GPS modul by tak měl mít vyvedeny ještě tyto piny na JST-GH konektoru:

- TIMEPULSE - výstup LED je potřeba posílit přes tranzistor, aby nedocházelo k výraznému zatěžování výstupu
- EXTINT - Bude využit pro časové značkování payloadem
- GEOFENCE_STAT - Může být využit pro řešení situace při letu mimo vyhrazený prostor
- GPS RXD - Pro možnost konfigurace GPS z payloadu
- GPS TXD - Pro příjem dat z GPS payloadem
- GPS SDA  (Optional) - Připojení GPS k payloadu při požadavku na jiný datový výstup, než který požaduje autopilot.
- GPS SCL  (Optional)
- GND

U všech pinů je na zvážení, zda je nějak chránit před přetížením payloadem, neboť chyba v payloadu by mohla mít fatální následky pro funkci celého systému. 

Nejjednodušší řešení je použít 1k rezistory sériově s výstupem RX/TX pro payload. Tím by mělo být zaručeno, ze autopilot bude mít vždy přednost v komunikaci.  Ostatní piny zřejmě stačí chránit před přetížením 33ohm sériovými resistory.

**Comment by ChroustJan** [comment]
Přidán konektor
