### ISSUE TITLE
Impedance připojení antény

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFGPS01#11]
Cesty na RF části by zřejmě alespoň přibližně měly být 50 Ohm. 

![image](https://user-images.githubusercontent.com/1194177/97094888-8a1d2b80-1659-11eb-99cf-52e238a4032f.png)

Takhle to dělá dojem, že je to úplně náhodné.

**Comment by ChroustJan** [comment]
Já 50 OHM přes to malé IO nedostanu. @kaklik myslíš že má smysl to vést kousek před to IO?

**Comment by kaklik** [comment]
> Já 50 OHM přes to malé IO nedostanu. @kaklik myslíš že má smysl to vést kousek před to IO?

Ano má..    

Jak  to, že na 4 vrstvým PCB nedáš dohromady 50 ohm?  To ti vyšlo v tom KiCAD kalkulátoru mikropáskových vedení?

**Comment by ChroustJan** [comment]
A ty ho umíš používat? Mě došlo že používám sílu cesty kterou jsem vypočetl pro 2V PCB.

**Comment by kaklik** [comment]
Celý je to o tom tam zadat správný parametry.
Já ale netušim jaký parametry má výrobce PCB pro 4V desku. 

Když se tam dá nějaký default, tak to vychází takhle: 

![image](https://user-images.githubusercontent.com/1194177/97215069-47c42d80-17c4-11eb-9d66-e0d3fdbb1629.png)


Ještě jsem si všiml, že je zřejmě problém, že pod tou RF cestou není jednolitá zem. Tím pádem se to nedá považovat za mikropáskový vedení a bude to mít zbytečně útlum a přeslechy. 

![image](https://user-images.githubusercontent.com/1194177/97214984-28c59b80-17c4-11eb-8558-35d256a5a29f.png)

**Comment by ChroustJan** [comment]
Provedena optimalizace

**Comment by kaklik** [comment]
Myslím si, že je na PCB potřeba lépe oddělit RF část.. Minimálně prošitím zemních ploch prokovy. 



Také jsem si všiml, že ploška pro připojení antény nerespektuje doporučený layout z datasheetu. Navíc až tak hrubým způsobem, že by pravděpodobně po zaletování antény došlo ke zkratu. 

![image](https://user-images.githubusercontent.com/1194177/97462268-d52b8d00-193e-11eb-86f0-ffe1203fe697.png)

**Comment by ChroustJan** [comment]
Ploška u antény změněna na 2,5mm.

**Comment by ChroustJan** [comment]
@kaklik  provedeš tu RF optimalizaci?

**Comment by kaklik** [comment]
> @kaklik provedeš tu RF optimalizaci?

Je nějaký důvod proč tahle napájecí cestá je ve žlutý vrstvě a nemuže být v zelený? 

![image](https://user-images.githubusercontent.com/1194177/97814991-65ddd200-1c8b-11eb-8e47-2416e4855065.png)

**Comment by kaklik** [comment]
> Ploška u antény změněna na 2,5mm.

Myslím, že to není uděláno správně, neboť tam šlo zejména o izolační mezeru okolo té plošky.

Nevím jak se to udělá správně. Nejak mi nejde nastavit aby okolo plošky průměru 2.5 mm bylo okruží bez mědi s průměrem 3.5mm.

**Comment by kaklik** [comment]
Tady jsem zjistil, že pouzdro zřejmě nemá ošetřeny zóny bez mědi, které vyžaduje datasheet: 

![image](https://user-images.githubusercontent.com/1194177/97816041-a68d1980-1c92-11eb-9204-6a3b5d164ec3.png)

![image](https://user-images.githubusercontent.com/1194177/97816053-b60c6280-1c92-11eb-88c9-5378c43fee84.png)

(šrafovaná oblast)

Jinak jsem pozice součástek poladil tak, jak si myslím, že by to mělo být propojené. Chybí tam ale: 

- [x] Ověřit šířku RF cest, aby to mělo 50 Ohm alespoň přibližně
- [x] Obšít to celé vias, aby byla izolovaná RF část od zbytku
- [x] Vyřešit potíž s ploškou antény
- [x] Zaoblit cesty nástrojem Fillet Tracks

**Comment by ChroustJan** [comment]
> > Ploška u antény změněna na 2,5mm.
> 
> Myslím, že to není uděláno správně, neboť tam šlo zejména o izolační mezeru okolo té plošky.
> 
> Nevím jak se to udělá správně. Nejak mi nejde nastavit aby okolo plošky průměru 2.5 mm bylo okruží bez mědi s průměrem 3.5mm.

A to něčemu vadí? Je tam přece ta vrstva lepidla.

**Comment by ChroustJan** [comment]
> > @kaklik provedeš tu RF optimalizaci?
> 
> Je nějaký důvod proč tahle napájecí cestá je ve žlutý vrstvě a nemuže být v zelený?
> 
> ![image](https://user-images.githubusercontent.com/1194177/97814991-65ddd200-1c8b-11eb-8e47-2416e4855065.png)

Tak nechceme mít pod tím IO žádné cesty. Tak jsem to dal aspoň do jiné vrstvy.

**Comment by kaklik** [comment]
> > > Ploška u antény změněna na 2,5mm.
> > 
> > 
> > Myslím, že to není uděláno správně, neboť tam šlo zejména o izolační mezeru okolo té plošky.
> > Nevím jak se to udělá správně. Nejak mi nejde nastavit aby okolo plošky průměru 2.5 mm bylo okruží bez mědi s průměrem 3.5mm.
> 
> A to něčemu vadí? Je tam přece ta vrstva lepidla.

Vadí to impedančnímu přizpůsobení.. Ta anténa je naladěná na tu geometrii, která je popsána v datasheetu.

**Comment by ChroustJan** [comment]
Chybí dořešit:
- [x] Ověřit šířku RF cest, aby to mělo 50 Ohm alespoň přibližně (https://www.gatema.cz/file-link/kriteria-dat-pro-pool-servis.pdf)
![image](https://user-images.githubusercontent.com/9783606/97874110-d1ba4c00-1d18-11eb-99f0-351cbfe65fe2.png)

- [x] Obšít to celé vias, aby byla izolovaná RF část od zbytku
- [x] Opravit zem
- [x] Vyřešit potíž s ploškou antény
- [x] ~~Zaoblit cesty nástrojem Fillet Tracks~~ - není co zaoblovat

**Comment by kaklik** [comment]
Tak jednotlivé body vyřešeny.  Stěžuje si to ale na DRC. Možná bude nutné ještě nějak poladit průměry a pozice těch vias.

**Comment by ChroustJan** [comment]
Vyřešeno.
