### ISSUE TITLE
Celistvost zemní plochy pod anténou

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFGPS01#13]
Možná by bylo užitečné prokovy, které jsou na zemní ploše patch antény rozdělit tak, aby netvořily skupiny, kde se nemůže dostat zem. 

![image](https://user-images.githubusercontent.com/1194177/97094976-4971e200-165a-11eb-87c7-5bc7fff7a19a.png)

**Comment by ChroustJan** [comment]
Vzato v potaz
