### ISSUE TITLE
Rozměry PCB

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFGPS01#16]
Rozměry a rozteč děr modulu jsou v současné době imperiální (podle MLAB vzoru).

Myslím si však, že je špatně nutit zákazníky používat imperiální míry a rozměry i rozteč děr by měla být metrická.

**Comment by ChroustJan** [comment]
Upraveno.

**Comment by kaklik** [comment]
Měřil jsem včera rozměr měděné plochy pod anténou. Je to teď něco jako 49.5mm a přitom je plocha až téměř do kraje desky, což asi nejde vyrobit.  Protože pro drážkování je vyžadován měděný motiv 0.4mm od kraje desky.

Datasheet antény ale požaduje rozměr vodivé plochy pod anténou 50 +/- 0.25mm. 

Nejlepším řešením zřejmě je zvětšit hranu desky na 51mm.

**Comment by ChroustJan** [comment]
Předělán rozměr na 51x51mm
