### ISSUE TITLE
Safety Switch LED

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFGPS01#19]
V aktuálním schéma je LED zapojená přímo na výstup pinu v sérii s rezistorem 620R. 

![image](https://user-images.githubusercontent.com/1194177/98294709-b10c2380-1fb0-11eb-8a35-6f6ee4ac6ba7.png)

Takové řešení ale zřejmě nebude fungovat, protože výstup pro LED je pouze 3.3V z nožičky MCU bez jakéhokoliv posílení. 

To je zmíněno i v dokumentu popisující standardní zapojení [Pixhawk konektorů](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-009%20Pixhawk%20Connector%20Standard.pdf)

![image](https://user-images.githubusercontent.com/1194177/98295074-414a6880-1fb1-11eb-90e8-76b3bde6bef8.png)

Je tak zřejmě nutné LED spínat přes tranzistor, pokud má rozumně svítit. 

Navíc k tomu je tam vysvětleno že SAFE_VCC se používá k napájení LED a SAFETY_SW.  
Což je důležitá poznámka, neboť konektor SAFETY SW v současném provedení má vyvedeno 5V napájení. SAFETY_SW vstup ale očekává 3.3V signalizaci.  SAFETY_LED bych ale z 3.3V z autopilota zřejmě asi osobně nenapájel, přijde mi to jako zbytečné zatěžování interního lineárního stabilizátoru, nerozumím však tomu, proč to mají tímto způsobem vymyšlené. Třeba je to důležité.   Tlačítko by ale z tohoto napájení zřejmě mělo být napájené.  V opačném případě by u tlačítka zřejmě měl být stabilizátor na 3.3V. Každopádně by pak ale vstup měl být nějak chráněn před připojením 5V na MCU. 

![image](https://user-images.githubusercontent.com/1194177/98295723-37753500-1fb2-11eb-8cc2-680403b6aa81.png)

**Comment by ChroustJan** [comment]
To je nějaké divné. Tohle jsme přece na začátku řešili, jak nato. Podle obrázku safetyswithe tady: https://github.com/ThunderFly-aerospace/TFGPS01/issues/6 se tam počítá s 5V, ale můžou to tam mít špatně. Nechápali jsme moc proč tam mají 2x5V. @kaklik je tedy potřeba se rozhodnout jak má být správně zapojený ten safetyswith.

**Comment by ChroustJan** [comment]
Vyřešena LED s tranzistorem

**Comment by kaklik** [comment]
> Vyřešena LED s tranzistorem

To je zřejmě správný krok. Neboť výstup pro LED je zapojen přes 100 Ohm rezistor. 

![image](https://user-images.githubusercontent.com/1194177/98353096-21ea2480-201f-11eb-851e-63842e76f675.png)

Je tak pravděpodobné, že by LED připojená přímo na výstup prakticky nesvítila.

**Comment by kaklik** [comment]
@roman-dvorak  vyfotil zapojení CUAV safety-switch. 

![124000558_710933332853973_5475796765917049213_n](https://user-images.githubusercontent.com/1194177/98353638-dedc8100-201f-11eb-83ad-f1a2706469f9.jpg)

LED je tam zapojena takto: 

![123742595_807826586678987_1704309623895534681_n](https://user-images.githubusercontent.com/1194177/98422106-20564600-208b-11eb-9f4c-49c74c3a2df5.jpg)

Takže výsledkem je, že je potřeba aby LED svítala při log0 na výstupu SAFETY_SW_LED.

Dále CUAV nevyužívá pin 1 u SAFETY_SW konektoru. Tím pádem je  možné na něj umístit SAFETY_VCC.

**Comment by ChroustJan** [comment]
Provedeny potřebné úpravy.

**Comment by kaklik** [comment]
SAFE_VCC musí být na pinu 1. Nikoliv na Pinu 5 

![image](https://user-images.githubusercontent.com/1194177/98461742-0c0b6980-21af-11eb-8826-c524c104ee30.png)


Upravil jsem to ve schéma. Ještě je to potřeba přeroutovat na plošném spoji.

**Comment by ChroustJan** [comment]
Oprava SAFE_VCC

**Comment by kaklik** [comment]
Vidím to zaroutováno i na plošném spoji. :)
