### ISSUE TITLE
USB konektor - pro nastavení

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFGPS01#2]
Doplnit malý USB konektor.
Možnosti jsou buď uUSB, nebo USB-C.

**Comment by kaklik** [comment]
Tady by se s tím USB mělo zřejmě zacházet jako s differenčním signálem. 

![image](https://user-images.githubusercontent.com/1194177/97094835-0400e500-1659-11eb-8e0e-dc3896efa02a.png)

Nějak taky nechápu to zapojení. Protože [tady](https://en.wikipedia.org/wiki/USB-C) USB 2.0 vidím pouze na jednom páru vodičů.

**Comment by ChroustJan** [comment]
Já to chápu tak, že tam je jeden pár, ale ten konektor jde otočit o 180stupňů. Tak si myslím, že nevíme jaké páry budou použity. Tady to používají jako my: https://forum.kicad.info/t/how-to-connect-a-ft232rl-to-a-usb-type-c-connector/18557/3

**Comment by kaklik** [comment]
> Já to chápu tak, že tam je jeden pár, ale ten konektor jde otočit o 180stupňů. Tak si myslím, že nevíme jaké páry budou použity. Tady to používají jako my: https://forum.kicad.info/t/how-to-connect-a-ft232rl-to-a-usb-type-c-connector/18557/3

A jaký přesně typ konektoru tam nakonec je? Můžeš prosím rovnou ve schéma vyplnit ten odkaz na datasheet, abych se mohl podívat do stejného dokumentu? 

No jestli je nutný zapojovat to USB 2.0 takhle hloupě, aby to fungovalo, tak je to pro mě překvapivý. 

Každopádně to nic nemění na tom, že by ty cesty měly být vedený alespoň jako differenční pár.

**Comment by ChroustJan** [comment]
Optimalizováno
