### ISSUE TITLE
Krabička pro GPS

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TFGPS01#21]
Typy krabiček:

 - [x] Krabička univerzální pro GPS pouze s USB konektorem.
 - [x] Krabička univerzální s přístupem ke všem kenektorům
 - [x] Krabička pro TF-G2
 - [x] Krabička na  TF-R2-mount
<hr>

Pro TF-G2 a tuto GPS byl připraven držák podle https://github.com/ThunderFly-aerospace/TF-G2/issues/71

Bylo by vhodné, aby GPS měla kryt, který zakryje patch anténu proti doteku rukou popř. dešti. Toho by šlo docílit následující konstrukcí:
![image](https://user-images.githubusercontent.com/5196729/99681771-d3a53e80-2a7e-11eb-83f5-2d428b2c399b.png)

GPS by se do krytu připevnila ze spodní strany. Horní vrstva by byla plná (tištěná na podložku). Stejným způsobem by měly být udělané průzory pro indikační LEDky. Tim by byla zajištěna i dobrá odolnost proti vodě. Z boku (přední, zadní strana) by byly otvory pro připojení kablíků. 

Alternativně by to šlo vyřešit tak, že by nebyly tištěné plné vrstvy a přes celou plochu by byla přelepena nějaká samolepící/krycí fólie. 

Pro samotnou krabičku není nutná řada otvorů po stranách. Ale nějaké montážní otvory by měly být připraveny.

**Comment by kaklik** [comment]
Příprava na samolepku je myslím dobrý nápad. 

Ještě té krabičce ale zřejmě bude potřeba ztenčit rantl, aby nedocházelo k warpování při tisku na studené podložce.

**Comment by kaklik** [comment]
Myslím že prakticky je to zatím vyřešené.

**Comment by roman-dvorak** [comment]
Ne, ještě je potřeba udělat úpravy krabičky pro TF-G2

Jsou tam potřeba tyto úpravy:
 * Matku vložit do kapsy. 
 * Odstranit rantl v místě konektorů - dost to znepříjemňuje odpojování konektorů.

**Comment by kaklik** [comment]
> Ne, ještě je potřeba udělat úpravy krabičky pro TF-G2
> 
> Jsou tam potřeba tyto úpravy:
> 
>     * Matku vložit do kapsy.
> 
>     * Odstranit rantl v místě konektorů - dost to znepříjemňuje odpojování konektorů.

Aha, ale to asi nikde nebylo napsaný.

**Comment by roman-dvorak** [comment]
Proto to také nebylo zaškrtlé

**Comment by roman-dvorak** [comment]
Úkoly pro dokončení krabičky ve vezi pro TF-G2:
 - [x] Zmenšit boční rantl (třeba aby vyčníval 1 mm nad okolní plochou). Díky tomu půjde snáze manipulovat s JST-GH konektory (odpojení/zapojení)
 - [x] Pro šroub vytvořit tunel (kostku), ve které bude schovaný.
 - [x] Vytvořit kapsu pro zapuštění matky. Jsou dvě možnosti, jak ji umístit (@kaklik???) Já jsem pro první variantu - pod samolepku. 
   1. z které strany kapsa má být. Mohla by být z vrchní strany, kde se schová pod samolepku #25. Díky tomu by matka byla pojištěna proti vypadnutí ale vyžadovalo by to, aby byla umístěna těsně pod povrchem. 
   2. Nebo ze spodní strany, kde se těžko nějakým způsobem zalepí, Pokud není zalepena, tak jakákoliv manipulace (odšroubování/zašroubování) je velmi náročný a dlouhý proces...

(doplním obrázek)

**Comment by kaklik** [comment]
@roman-dvorak  nevím, kterou matici myslíš, takže to těžko můžu nějak rozhodovat.   Kromě klasických matic ale existuje ještě i [toto řešení](https://www.tme.eu/en/katalog/threaded-insertions_112546/?s_order=desc&search=M3%20do%20plastu&s_field=1000011). Asi není nutné všude trvat na maticích, pokud to v tom případě je nevhodné.

**Comment by llucka** [comment]
úkoly splněny

**Comment by kaklik** [comment]
@llucka  super!  :)  @roman-dvorak  Mám to nějak tisknout já, nebo to nějak ověříte na vírníku?

**Comment by roman-dvorak** [comment]
Vytiskl jsem tu krabičk pro TF-G2, myslím, že spňuje požadavky. Je tedy možné na to navrhnout samolepku #25, která zároveň bude držet matku. 

![20210504_144241](https://user-images.githubusercontent.com/5196729/117005526-a58f8000-ace7-11eb-831b-6464c84b8c0b.jpg)

![20210504_144255_HDR](https://user-images.githubusercontent.com/5196729/117005535-a9bb9d80-ace7-11eb-90dc-d1e7adb07d96.jpg)

> (tištěno z nějakého staršího neznámého PLA vzorku, takže z polymaxu to bude myslím dobré)
