### ISSUE TITLE
Rozdíl mezi safety LED signály z autopilotů

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TFGPS01#22]
Při prvním zapojení GPS do autopilotů CUAV NANO a CUAV V5+ bylo zjištěno jejich rozdílné chování. 

**Při zapojení do CUAV v5+:**
bez zapojeného safety tlačítka ARM ledka svítí stále. Je vidět nevýrazná změna intenzity svitu. 
Při zapojení safety tlačítka LED na GPS bliká (asi ve správné polaritě) a led na tlačítku stále svítí. 

**Při zapojení do CUAV NANO**
ARM ledka funguje tak, jak má. 

Tlačítko funguje u obou stejně, tak, jak má. 

Pípák také funguje. Pocitově by mohl být hlasitější.

**Comment by roman-dvorak** [comment]
Po reálných pokusech se zdá, že hlasitost pípáku stačí.

**Comment by roman-dvorak** [comment]
# CUAV NANO

![obrazek](https://user-images.githubusercontent.com/5196729/105472747-98043c00-5c9c-11eb-99a0-1999cfa2cfd8.png)

SAFETY_IN - přpojeno přes 100R do FMU procesoru a přes 1k5 do GND
SWITCH_LED - připojeno přes 100R do FMU
SAFE_VCC - připojeno na IO 3v3
BUZZER - připojeno přímo do FMU (bez jakéhokoliv odporu) 


# CUAV V5+

![obrazek](https://user-images.githubusercontent.com/5196729/105473428-68096880-5c9d-11eb-9917-d3a354df3b12.png)

![obrazek](https://user-images.githubusercontent.com/5196729/105473745-bc144d00-5c9d-11eb-8ba9-4629cbf52c26.png)

SAFETY_IN - přpojeno přes 100R do FMU a přes 100R do IO a přes 1k5 do GND
SWITCH_LED - přes 100R do FMU a přes 100R do IO
SAFE_VCC - do 3v3
BUZZER - připojeno přímo do FMU - PE5 (bez jakéhokoliv odporu) 


U CAV V5+ je rozdíl, že LED a SW_SWITCH jsou paraelně přípojené do FMU a IO procesoru. Jinak zapojení jsou ekvivalentní.

**Comment by kaklik** [comment]
Myslím že hlavní problém tohoto issue spočívá v tom, že SAFETY_SW_LED ovládá bázi tranzistoru Q3 přes 100 Ohm rezistor. Výstup z MCU je tak přetížen. 

![image](https://user-images.githubusercontent.com/1194177/116552668-92e90580-a8f9-11eb-84af-c5a833af2682.png)

Je tak nutné R28 na TFGPS vyměnit za větší hodnotu. A vyzkoušet, zda to povede k vyřešení problému. 
Vhodná hodnota rezistoru R28 může být podle hrubého odhadu (při [zesílení tranzistoru Q3](https://assets.nexperia.com/documents/data-sheet/BC817_SER.pdf) asi 160) někde mezi 4k7 a 10k.

**Comment by roman-dvorak** [comment]
Vyzkoušel jsem změnit R28 za 10k rezistor. S CUAV safety tlačítkem bliká jak tlačítko, tak LEDka na TFGPS. (Což považuji za správný stav)

**Comment by roman-dvorak** [comment]
Aktuální stav:

CUAV NANO - chová se dle očekávání
Bliká se správnou polaritou s i bez připojeného tlačítka

CUAV V5+
Bliká správně s připojeným tlačítkem (jak LED na GPS tak i na tlačítku) 
Bez přípojeného tlačítka LED na GPS svítí stále. Na SAFETY_SW_LED pinu je 0.1-0.2V periodicky 0.0V (v okamžiku, kdy má svítit)


### Při měření přímo na výstupu z autopilota (s odpojením tlačítkem i GPS):
Nano: Skáče z 3v3 na 0V
V5+: 0.1-0.2V

**Comment by roman-dvorak** [comment]
Přidání rezistoru 10k mezi SAFETY_SW_LED a SAFETY_VCC vyřešilo problém neustále svítící LEDky u CUAV V5+

Ve všech kombinacích se (Nano vs V5+; bez tlačítka vs s tlačítkem) se to chová dle očekávání. 


Poslední věc je, že u CUAV V5+ tlačítko ve zhasnutém stavu velmi nevýrazně "prosvítá". Ale je to pozorováno v dost tmavém prostředí. Rozdíl svítí/nesvítí je velmi velký.  (u CUAV nano se to neděje)

Při přímém zapojení tlačítka do autopilota LEDka neprosvítá (ani u jednoho autopilota)

**Comment by roman-dvorak** [comment]
Po zvětšení rezistoru R28 na 20k tlačítko svítí opravdu nepatrně. (V místnosti musí být úplná tma).  (CUAV V5+ s TFGPS a Tlačítkem) 

CUAV V5+ + GPS + Tlačítko - OK
CUAV V5+ + GPS - OK
CUAV V5+ Tlačítko - Ok

Nano + GPS + Tlačítko - OK
Nano + GPS - OK
Nano + Tlačítko - OK


#  Potřebné změny:
 * R28 - 20k  (může být větší)
 * Mezi SAFETY_VCC a SAFETY_SW_LED přidán pulllup rezistor 10k

> Pullup lze umíst vedle SAFETY_SW konektoru s minimálními úpravami v routování na PCB.

**Comment by ChroustJan** [comment]
![image](https://user-images.githubusercontent.com/9783606/120764730-bf0b2e00-c518-11eb-8532-9199fa940b97.png)
