### ISSUE TITLE
Možnost přepínání low/high LNA gain mode

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFGPS01#23]
Resistorem R26, respektive jeho připojením na GND nebo VCC lze ovlivnit zda LNA (MAX2656) bude v high-gain nebo low-gain mode. 

V aktuální verzi je tento rezistor připojen trvale na Vcc. Což odpovídá nastavení low-gain mode. To je důležité kvůli vyšší odolnosti GPS přijímače proti elektromagnetickému rušení. IIP3 zesilovače je tak +8 dBm místo +1 dBm.

Toto nastavení je vhodné pro použití GPS pod volnou oblohou, kde není problém s úrovní signálu.  Znemožňuje však použití v zastíněných oblastech, kde dostupnost signálu není tak dobrá, nebo při testech uvnitř budov. 

Možná by tak chtělo zvážit nějakou možnost přepínání

**Comment by kaklik** [comment]
Zatím tohle přepínání nebylo vyzkoušeno protože do GPS byl osazen jiný typ LNA, než je ve schéma.  Osazený typ se při přepnutí disabluje.

**Comment by ChroustJan** [comment]
@kaklik takže tento odpor R26 má mít možnost být na VCC nebo GND?
![image](https://user-images.githubusercontent.com/9783606/116566187-d4cc7880-a906-11eb-8a35-ff7e7510a8a5.png)

**Comment by kaklik** [comment]
> @kaklik takže tento odpor R26 má mít možnost být na VCC nebo GND?
> 

Ano, z hlediska ovlivnění současného designu by bylo lepší tohle přepínání udělat ještě před R23.  Aby přepínač nemohl ovlivnit aktuální RF layout. 
Jak ale píšu výše, tohle přepínání ještě nebylo vyzkoušeno, protože žádná GPS nebyla osazena obvodem MAX2656.

**Comment by kaklik** [comment]
Podle aktuálních zjištění MAX2656 zřejmě již není dobře dostupný, proto tato úprava nemá význam.
