### ISSUE TITLE
Zatížení výstupů  "posilujícími" tranzistory 

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFGPS01#24]
Výstupy jsou zatíženy tranzitory, které mají budit LED.  Ve skutečnosti je ale více zatěžují, než samotné LED.

![image](https://user-images.githubusercontent.com/1194177/100019785-f026db00-2dde-11eb-9c2b-a72710797609.png)

Důvodem je, že v bázi jsou pouze 100 ohm rezistory, tudíž do báze teče (3.3-0.7)/100 což je 26mA.

Podle [datasheet k tranzistorům](https://assets.nexperia.com/documents/data-sheet/BC817_SER.pdf)  vůbec neuvažuje větší kontinuální proud bázi než 16 mA.  Zesílení tranzistoru je minimálně 160.  Takže pro proud LED třeba 30 mA, stačí proud báze maximálně 0.18 mA.

**Comment by ChroustJan** [comment]
Dán odpor 10k.
