### ISSUE TITLE
Štítek pro TFGPS

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TFGPS01#25]
Navrhnout samolepky pro krabičku (#21) Ve dvou verzích:
 - [x] Samostatná krabička
 - [x] Pro TF-G2 (má jiný vnější rozměr) - možná pouze jiný ořez. 

Samolepka realizovaná pro TFRMP se zdá použitelná.

**Comment by kaklik** [comment]
Tohle je myslím aktuálně vyřešené.
