### ISSUE TITLE
Výběr integrované antény

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFGPS01#3]
K modulu je potřeba vybrat GPS patch anténu, která bude mít relativně dobrý zisk a účinnost.  
Měla by také být poměrně úzkopásmová, aby se minimalizovala zátěž přezesilovače rušivými signály.

**Comment by kaklik** [comment]
@ChroustJan našel následující dva typy: 

![76260604_270836094184106_1735616764246143156_n](https://user-images.githubusercontent.com/1194177/86284205-b7ddf080-bbe2-11ea-9e4f-7bb7fbc68c11.png)

Vhodnější je zřejmě ten s nižší hmotností [CGGBP.35.3.A.02](https://www.taoglas.com/product/cggbp-35-3-a-02-gpsglonassbeidou-patch-antenna-353mm-2/), datasheet je k dispozici [zde](https://cz.mouser.com/datasheet/2/398/CGGBP.35.3.A.02-1-1218655.pdf). Anténa je naladěna na čtvercový ground-plane o hraně 70mm.  Alternativou k této anténě je o [půl milimetru tlustší pro automotive aplikace](https://www.taoglas.com/product/cggp-35-3-a-02-gpsglonass-dual-band-patch-antenna-35353-5mm-2/), ta zároveň vyhovuje automotive standardu TS16949. datasheet je k disipozici [zde](https://cz.mouser.com/datasheet/2/398/CGGP.35.3.A.02-27913.pdf).  **Tento typ je naladěn na menší ground plane o hraně 50mm, pro zvolenou aplikaci je tak zřejmě vhodnější.**

**Comment by ChroustJan** [comment]
@kaklik takže chceme tuto anténu: CGGP.35.3.A.02 ?

**Comment by kaklik** [comment]
> @kaklik takže chceme tuto anténu: CGGP.35.3.A.02 ?

Ano
