### ISSUE TITLE
Výběr vstupních obvodů RF signálu

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFGPS01#4]
RF signá z antény #3  je potřeba zesílit, tak aby jeho hodnoty byly odpovídající vstupním požadavkům uBlox GPS modulu. 

Zesilovač musí mít dobrou selektivitu (SAW filtr) a hlavně vysokou odolnost (IIP3), aby nemohl být snadno zahlcen mimopásmovým signálem. Tato vlastnost je pravděpodobně spojena s vyšší energetickou spotřebou zesilovače. 

Vstupní obvody by měly umožňovat deaktivaci integrované antény, aby bylo možné připojit externím konektorem MCX kvalitnější, nebo lépe umístěnou externí anténu.

**Comment by kaklik** [comment]
## Vhodné LNA

- [MAX2659](https://www.maximintegrated.com/en/design/technical-documents/app-notes/4/4264.html) - má logický vstup pro vypnutí, IP3 má -0.5 dBm nebo až +6.2 dBm s přidanou indukčností. 
- [BGA925L6](https://www.infineon.com/dgdl/AN265.pdf?fileId=db3a3043327f13e30132a501b14a434f) - IIP3 až +7dBm, ale má docela šílené pouzdro. 
- [MAX2676](https://www.mouser.com/datasheet/2/256/MAX2674-MAX2676-1292129.pdf) - IIP3 +5 dBm, anténní přepínač s "autodetekcí připojení antény". (0.86mm x 1.26mm) WLP Package
- **[MAX2656](https://www.maximintegrated.com/en/products/comms/wireless-rf/MAX2656.html) - IIP3 nastavitelná až 7.2 dBm, celkem normální pouzdro**


## Vhodné SAW

Zde je [dokument s doporučenými SAW filtry](https://www.u-blox.com/sites/default/files/products/documents/GLONASS-HW-Design_AppNote_%28GPS.G6-CS-10005%29.pdf) od uBlox. 

- **[DBP.1575.W.A.30](https://eu.mouser.com/ProductDetail/Taoglas/DBP1575WA30?qs=MLItCLRbWszB%2FaCDsG6gyg%3D%3D) - rozumně pájitelné pouzdro**
- [SAFEA1G58KA0F00](https://static6.arrow.com/aropdfconversion/8a9a7452915a657d071f3b570b23f3be0ff40663/safea1g58ka0f00_ds.pdf) -  velmi malé pouzdro
- [TFS1575D](https://www.vectron.com/products/saw/pdf_saw/TFS1575D.pdf)

**Comment by kaklik** [comment]
Ten MAX2656 je potřeba přepnout do Low-gain mode (Note 12).  V kombinaci s Rbias = 392 Ohm.

**Comment by ChroustJan** [comment]
Aplikováno.
