### ISSUE TITLE
Konektory

### ISSUE THREAD

**Issue by ChroustJan** [ThunderFly-aerospace/TFGPS01#6]
Pro propojení s autopilotem tento:
![image](https://user-images.githubusercontent.com/9783606/95582572-1e24ab80-0a3b-11eb-8bab-1c97f2477847.png)

Modul by měl mít i výstup na safetyswith:
![image](https://user-images.githubusercontent.com/9783606/95583080-e702ca00-0a3b-11eb-809d-c1e9334fa4ba.png)

Rozložení pinů u autopilota:
http://doc.cuav.net/flight-controller/v5-autopilot/en/v5+.html#connection

Pro anténu MCX

**Comment by ChroustJan** [comment]
SAFE_VCC k čemu slouží?

**Comment by kaklik** [comment]
> SAFE_VCC k čemu slouží?

Netuším k čemu slouží, ale podle tohoto schéma: https://github.com/cuav/hardware/blob/master/V5_Autopilot/V5_NANO/RC03/V5_NANO_RC03.pdf
 
Vzniká na U 13, což je LDO, takže bych ho pro napájení GPS modulu nevyužíval.
