### ISSUE TITLE
Záložní zdroj pro paměť GPS při výpadku napájení

### ISSUE THREAD

**Issue by ChroustJan** [ThunderFly-aerospace/TFGPS01#8]
Doposud byl aplikován 1F kondenzátor. Zde je to nevhodné.

![image](https://user-images.githubusercontent.com/9783606/95728164-79dd7780-0c7b-11eb-98b5-e6c0f1a21c77.png)

**Comment by ChroustJan** [comment]
https://www.tme.eu/cz/details/fcs0h104zftbr24/superkondenzatory/kemet/

**Comment by kaklik** [comment]
V tomto schématu by bylo možné použít například tento kondenzátor: https://www.tme.eu/cz/details/fc0h104zftbr24/superkondenzatory/kemet/ Který je možné nabíjet rovnou z 5V zdroje.  Backup napájení ublox modulu ale nevydrží více než 3.6V Takže napájení z 3.3V je nutné zachovat.

**Comment by ChroustJan** [comment]
Vhodný kondenzátor je tento: https://www.tme.eu/cz/details/fcs0h104zftbr24/superkondenzatory/kemet/ bude nahrazen v zapojení za C1. Odpor a dioda bude zachována.
